### ISSUE TITLE
Make the order of condition blocks not matter

### ISSUE THREAD

**Issue by ErichDonGubler** [ErichDonGubler/adhesion-rs#1]
It feels unergonomic to have these in a fixed order. Is it possible to leave the order up to the user with macros by example?

**Comment by dzamlo** [comment]
You may look at the way [error-chain](https://github.com/brson/error-chain/blob/3d0df86984a167db97ae2b6649d91f7d2c57c6a0/src/error_chain.rs#L330-L394) does it.

**Comment by ErichDonGubler** [comment]
Thanks again, @dzamlo! You've had some awesome pointers. :)
