### ISSUE TITLE
Wean ourselves off of nightly

### ISSUE THREAD

**Issue by ErichDonGubler** [ErichDonGubler/adhesion-rs#2]
The `fn_traits` feature is all that's really needed here. Perhaps we just need to wait until it stabilizes?

**Comment by dzamlo** [comment]
You can just call the closure directly:
```rust
let $return_value = inner($($args),*);
```
Or am I missing something ?


On a related note, the closure could just be a `fn` instead of a closure:
```rust
fn inner($($args : $types),*) ->$return_type {
    $body
}
```
But I'm not sure of what that would changes.

**Comment by ErichDonGubler** [comment]
@dzamlo Haha, writing this at 3 in the morning obviously did a number on me. Seems obvious in retrospect, especially because I already did something similar with the lambda definition, like you showed! TIL, thanks!
